# Generated by biab-dev/scripts/gen-social-tables.ts — DO NOT EDIT.
# Source of truth: biab-dev/src/socials.ts. Run `pnpm gen:socials`.

defmodule BiabStarter.Biab.SocialPlatforms do
  @moduledoc """
  The social platforms a company profile can advertise, in canonical render
  order. Generated from biab-dev/src/socials.ts.
  """

  @all [
    %{key: "meta", label: "Facebook", icon_slug: "facebook", href_prefix: "https://facebook.com/"},
    %{key: "instagram", label: "Instagram", icon_slug: "instagram", href_prefix: "https://instagram.com/"},
    %{key: "twitterX", label: "X", icon_slug: "x", href_prefix: "https://x.com/"},
    %{key: "tikTok", label: "TikTok", icon_slug: "tiktok", href_prefix: "https://tiktok.com/@"},
    %{key: "youTube", label: "YouTube", icon_slug: "youtube", href_prefix: "https://youtube.com/"},
    %{key: "linkedIn", label: "LinkedIn", icon_slug: "linkedin", href_prefix: "https://linkedin.com/"},
    %{key: "pinterest", label: "Pinterest", icon_slug: "pinterest", href_prefix: "https://pinterest.com/"},
    %{key: "threads", label: "Threads", icon_slug: "threads", href_prefix: "https://threads.net/@"},
    %{key: "bluesky", label: "Bluesky", icon_slug: "bluesky", href_prefix: nil},
    %{key: "mastodon", label: "Mastodon", icon_slug: "mastodon", href_prefix: nil},
    %{key: "truthSocial", label: "Truth Social", icon_slug: "truthsocial", href_prefix: nil},
    %{key: "googleBusiness", label: "Google", icon_slug: "google", href_prefix: nil},
    %{key: "yelp", label: "Yelp", icon_slug: "yelp", href_prefix: nil},
    %{key: "nextdoor", label: "Nextdoor", icon_slug: "nextdoor", href_prefix: nil},
    %{key: "angi", label: "Angi", icon_slug: nil, href_prefix: nil},
    %{key: "homeAdvisor", label: "HomeAdvisor", icon_slug: nil, href_prefix: nil},
    %{key: "houzz", label: "Houzz", icon_slug: "houzz", href_prefix: nil},
    %{key: "thumbtack", label: "Thumbtack", icon_slug: "thumbtack", href_prefix: nil},
    %{key: "bbb", label: "Better Business Bureau", icon_slug: nil, href_prefix: nil},
    %{key: "whatsApp", label: "WhatsApp", icon_slug: "whatsapp", href_prefix: "https://wa.me/"},
    %{key: "discord", label: "Discord", icon_slug: "discord", href_prefix: nil},
    %{key: "substack", label: "Substack", icon_slug: "substack", href_prefix: nil},
    %{key: "reddit", label: "Reddit", icon_slug: "reddit", href_prefix: nil},
    %{key: "buyMeACoffee", label: "Buy Me a Coffee", icon_slug: "buymeacoffee", href_prefix: nil},
    %{key: "kofi", label: "Ko-fi", icon_slug: "kofi", href_prefix: nil},
    %{key: "patreon", label: "Patreon", icon_slug: "patreon", href_prefix: nil},
    %{key: "twitch", label: "Twitch", icon_slug: "twitch", href_prefix: nil},
    %{key: "vimeo", label: "Vimeo", icon_slug: "vimeo", href_prefix: nil},
    %{key: "github", label: "GitHub", icon_slug: "github", href_prefix: "https://github.com/"},
    %{key: "behance", label: "Behance", icon_slug: "behance", href_prefix: nil},
    %{key: "dribbble", label: "Dribbble", icon_slug: "dribbble", href_prefix: nil}
  ]

  @doc "Every known platform, in canonical order."
  def all, do: @all
end
