<?php
// Generated by biab-dev/scripts/gen-social-tables.ts — DO NOT EDIT.
// Source of truth: biab-dev/src/socials.ts. Run `pnpm gen:socials`.

declare(strict_types=1);

namespace App\Biab;

final class SocialPlatforms
{
    /** Canonical order — the order links should render in. */
    public const ALL = [
        ['key' => "meta", 'label' => "Facebook", 'iconSlug' => "facebook", 'hrefPrefix' => "https://facebook.com/"],
        ['key' => "instagram", 'label' => "Instagram", 'iconSlug' => "instagram", 'hrefPrefix' => "https://instagram.com/"],
        ['key' => "twitterX", 'label' => "X", 'iconSlug' => "x", 'hrefPrefix' => "https://x.com/"],
        ['key' => "tikTok", 'label' => "TikTok", 'iconSlug' => "tiktok", 'hrefPrefix' => "https://tiktok.com/@"],
        ['key' => "youTube", 'label' => "YouTube", 'iconSlug' => "youtube", 'hrefPrefix' => "https://youtube.com/"],
        ['key' => "linkedIn", 'label' => "LinkedIn", 'iconSlug' => "linkedin", 'hrefPrefix' => "https://linkedin.com/"],
        ['key' => "pinterest", 'label' => "Pinterest", 'iconSlug' => "pinterest", 'hrefPrefix' => "https://pinterest.com/"],
        ['key' => "threads", 'label' => "Threads", 'iconSlug' => "threads", 'hrefPrefix' => "https://threads.net/@"],
        ['key' => "bluesky", 'label' => "Bluesky", 'iconSlug' => "bluesky", 'hrefPrefix' => null],
        ['key' => "mastodon", 'label' => "Mastodon", 'iconSlug' => "mastodon", 'hrefPrefix' => null],
        ['key' => "truthSocial", 'label' => "Truth Social", 'iconSlug' => "truthsocial", 'hrefPrefix' => null],
        ['key' => "googleBusiness", 'label' => "Google", 'iconSlug' => "google", 'hrefPrefix' => null],
        ['key' => "yelp", 'label' => "Yelp", 'iconSlug' => "yelp", 'hrefPrefix' => null],
        ['key' => "nextdoor", 'label' => "Nextdoor", 'iconSlug' => "nextdoor", 'hrefPrefix' => null],
        ['key' => "angi", 'label' => "Angi", 'iconSlug' => null, 'hrefPrefix' => null],
        ['key' => "homeAdvisor", 'label' => "HomeAdvisor", 'iconSlug' => null, 'hrefPrefix' => null],
        ['key' => "houzz", 'label' => "Houzz", 'iconSlug' => "houzz", 'hrefPrefix' => null],
        ['key' => "thumbtack", 'label' => "Thumbtack", 'iconSlug' => "thumbtack", 'hrefPrefix' => null],
        ['key' => "bbb", 'label' => "Better Business Bureau", 'iconSlug' => null, 'hrefPrefix' => null],
        ['key' => "whatsApp", 'label' => "WhatsApp", 'iconSlug' => "whatsapp", 'hrefPrefix' => "https://wa.me/"],
        ['key' => "discord", 'label' => "Discord", 'iconSlug' => "discord", 'hrefPrefix' => null],
        ['key' => "substack", 'label' => "Substack", 'iconSlug' => "substack", 'hrefPrefix' => null],
        ['key' => "reddit", 'label' => "Reddit", 'iconSlug' => "reddit", 'hrefPrefix' => null],
        ['key' => "buyMeACoffee", 'label' => "Buy Me a Coffee", 'iconSlug' => "buymeacoffee", 'hrefPrefix' => null],
        ['key' => "kofi", 'label' => "Ko-fi", 'iconSlug' => "kofi", 'hrefPrefix' => null],
        ['key' => "patreon", 'label' => "Patreon", 'iconSlug' => "patreon", 'hrefPrefix' => null],
        ['key' => "twitch", 'label' => "Twitch", 'iconSlug' => "twitch", 'hrefPrefix' => null],
        ['key' => "vimeo", 'label' => "Vimeo", 'iconSlug' => "vimeo", 'hrefPrefix' => null],
        ['key' => "github", 'label' => "GitHub", 'iconSlug' => "github", 'hrefPrefix' => "https://github.com/"],
        ['key' => "behance", 'label' => "Behance", 'iconSlug' => "behance", 'hrefPrefix' => null],
        ['key' => "dribbble", 'label' => "Dribbble", 'iconSlug' => "dribbble", 'hrefPrefix' => null],
    ];
}
