// Generated by biab-dev/scripts/gen-social-tables.ts — DO NOT EDIT.
// Source of truth: biab-dev/src/socials.ts. Run `pnpm gen:socials`.

import Foundation

public struct SocialPlatform: Sendable, Hashable {
    public let key: String
    public let label: String
    public let iconSlug: String?
    public let hrefPrefix: String?
}

public enum SocialPlatforms {
    /// Canonical order — the order links should render in.
    public static let all: [SocialPlatform] = [
        SocialPlatform(key: "meta", label: "Facebook", iconSlug: "facebook", hrefPrefix: "https://facebook.com/"),
        SocialPlatform(key: "instagram", label: "Instagram", iconSlug: "instagram", hrefPrefix: "https://instagram.com/"),
        SocialPlatform(key: "twitterX", label: "X", iconSlug: "x", hrefPrefix: "https://x.com/"),
        SocialPlatform(key: "tikTok", label: "TikTok", iconSlug: "tiktok", hrefPrefix: "https://tiktok.com/@"),
        SocialPlatform(key: "youTube", label: "YouTube", iconSlug: "youtube", hrefPrefix: "https://youtube.com/"),
        SocialPlatform(key: "linkedIn", label: "LinkedIn", iconSlug: "linkedin", hrefPrefix: "https://linkedin.com/"),
        SocialPlatform(key: "pinterest", label: "Pinterest", iconSlug: "pinterest", hrefPrefix: "https://pinterest.com/"),
        SocialPlatform(key: "threads", label: "Threads", iconSlug: "threads", hrefPrefix: "https://threads.net/@"),
        SocialPlatform(key: "bluesky", label: "Bluesky", iconSlug: "bluesky", hrefPrefix: nil),
        SocialPlatform(key: "mastodon", label: "Mastodon", iconSlug: "mastodon", hrefPrefix: nil),
        SocialPlatform(key: "truthSocial", label: "Truth Social", iconSlug: "truthsocial", hrefPrefix: nil),
        SocialPlatform(key: "googleBusiness", label: "Google", iconSlug: "google", hrefPrefix: nil),
        SocialPlatform(key: "yelp", label: "Yelp", iconSlug: "yelp", hrefPrefix: nil),
        SocialPlatform(key: "nextdoor", label: "Nextdoor", iconSlug: "nextdoor", hrefPrefix: nil),
        SocialPlatform(key: "angi", label: "Angi", iconSlug: nil, hrefPrefix: nil),
        SocialPlatform(key: "homeAdvisor", label: "HomeAdvisor", iconSlug: nil, hrefPrefix: nil),
        SocialPlatform(key: "houzz", label: "Houzz", iconSlug: "houzz", hrefPrefix: nil),
        SocialPlatform(key: "thumbtack", label: "Thumbtack", iconSlug: "thumbtack", hrefPrefix: nil),
        SocialPlatform(key: "bbb", label: "Better Business Bureau", iconSlug: nil, hrefPrefix: nil),
        SocialPlatform(key: "whatsApp", label: "WhatsApp", iconSlug: "whatsapp", hrefPrefix: "https://wa.me/"),
        SocialPlatform(key: "discord", label: "Discord", iconSlug: "discord", hrefPrefix: nil),
        SocialPlatform(key: "substack", label: "Substack", iconSlug: "substack", hrefPrefix: nil),
        SocialPlatform(key: "reddit", label: "Reddit", iconSlug: "reddit", hrefPrefix: nil),
        SocialPlatform(key: "buyMeACoffee", label: "Buy Me a Coffee", iconSlug: "buymeacoffee", hrefPrefix: nil),
        SocialPlatform(key: "kofi", label: "Ko-fi", iconSlug: "kofi", hrefPrefix: nil),
        SocialPlatform(key: "patreon", label: "Patreon", iconSlug: "patreon", hrefPrefix: nil),
        SocialPlatform(key: "twitch", label: "Twitch", iconSlug: "twitch", hrefPrefix: nil),
        SocialPlatform(key: "vimeo", label: "Vimeo", iconSlug: "vimeo", hrefPrefix: nil),
        SocialPlatform(key: "github", label: "GitHub", iconSlug: "github", hrefPrefix: "https://github.com/"),
        SocialPlatform(key: "behance", label: "Behance", iconSlug: "behance", hrefPrefix: nil),
        SocialPlatform(key: "dribbble", label: "Dribbble", iconSlug: "dribbble", hrefPrefix: nil)
    ]
}
