// Generated by sdk/scripts/gen-social-tables.ts — DO NOT EDIT.
// Source of truth: sdk/src/socials.ts. Run `pnpm gen:socials`.

package app.bd

public data class SocialPlatform(
    val key: String,
    val label: String,
    val iconSlug: String?,
    val hrefPrefix: String?,
)

/** Canonical order — the order links should render in. */
public val SOCIAL_PLATFORMS: List<SocialPlatform> = listOf(
    SocialPlatform("meta", "Facebook", "facebook", "https://facebook.com/"),
    SocialPlatform("instagram", "Instagram", "instagram", "https://instagram.com/"),
    SocialPlatform("twitterX", "X", "x", "https://x.com/"),
    SocialPlatform("tikTok", "TikTok", "tiktok", "https://tiktok.com/@"),
    SocialPlatform("youTube", "YouTube", "youtube", "https://youtube.com/"),
    SocialPlatform("linkedIn", "LinkedIn", "linkedin", "https://linkedin.com/"),
    SocialPlatform("pinterest", "Pinterest", "pinterest", "https://pinterest.com/"),
    SocialPlatform("threads", "Threads", "threads", "https://threads.net/@"),
    SocialPlatform("bluesky", "Bluesky", "bluesky", null),
    SocialPlatform("mastodon", "Mastodon", "mastodon", null),
    SocialPlatform("truthSocial", "Truth Social", "truthsocial", null),
    SocialPlatform("googleBusiness", "Google", "google", null),
    SocialPlatform("yelp", "Yelp", "yelp", null),
    SocialPlatform("nextdoor", "Nextdoor", "nextdoor", null),
    SocialPlatform("angi", "Angi", null, null),
    SocialPlatform("homeAdvisor", "HomeAdvisor", null, null),
    SocialPlatform("houzz", "Houzz", "houzz", null),
    SocialPlatform("thumbtack", "Thumbtack", "thumbtack", null),
    SocialPlatform("bbb", "Better Business Bureau", null, null),
    SocialPlatform("whatsApp", "WhatsApp", "whatsapp", "https://wa.me/"),
    SocialPlatform("discord", "Discord", "discord", null),
    SocialPlatform("substack", "Substack", "substack", null),
    SocialPlatform("reddit", "Reddit", "reddit", null),
    SocialPlatform("buyMeACoffee", "Buy Me a Coffee", "buymeacoffee", null),
    SocialPlatform("kofi", "Ko-fi", "kofi", null),
    SocialPlatform("patreon", "Patreon", "patreon", null),
    SocialPlatform("twitch", "Twitch", "twitch", null),
    SocialPlatform("vimeo", "Vimeo", "vimeo", null),
    SocialPlatform("github", "GitHub", "github", "https://github.com/"),
    SocialPlatform("behance", "Behance", "behance", null),
    SocialPlatform("dribbble", "Dribbble", "dribbble", null),
)
